version: '3'
services:
  qdrant:
    image: hub.hamdocker.ir/qdrant/qdrant:v1.9.0
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data_new:/qdrant/storage
    environment:
      QDRANT__STORAGE__SNAPSHOTS__DIR: '/qdrant/snapshots'
volumes:
  qdrant_data_new: